server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8881/
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"